services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app # Mount source code for hot reload
      - nestjs_node_modules:/usr/src/app/node_modules # Anonymous volume to protect container's node_modules
    environment:
      - DATABASE_URL=mongodb://${DB_USERNAME}:${DB_PASSWORD}@db:27017/${DB_APP_NAME}?authSource=admin

  db:
    image: mongo:7.0.0
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db # Use named volume for data persistence
      - mongo_config:/data/configdb # Use named volume for config persistence

volumes:
  mongo_data:
  mongo_config:
  nestjs_node_modules: