services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
      - kafka
      - redis
    volumes:
      - .:/usr/src/app # Mount source code for hot reload
      - nestjs_node_modules:/usr/src/app/node_modules # Anonymous volume to protect container's node_modules
    environment:
      - DATABASE_URL=mongodb+srv://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}/${DB_APP_NAME}?authSource=admin
      - KAFKA_BROKER=${KAFKA_BROKER}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    restart: unless-stopped

  db:
    image: mongo:7.0.0
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db # Use named volume for data persistence
      - mongo_config:/data/configdb # Use named volume for config persistence

  kafka:
    image: apache/kafka:3.7.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"  # External listener for host machine
    environment:
      # KRaft mode configuration (no Zookeeper needed)
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      # port for kafka 9092 (Docker), 9093 (Controller), 9094 (Mac)
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      # KRaft cluster ID (randomly generated, keep consistent)
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    volumes:
      - kafka_data:/var/lib/kafka/data
      - kafka_secrets:/etc/kafka/secrets
      - kafka_config:/mnt/shared/config
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

volumes:
  mongo_data:
  mongo_config:
  nestjs_node_modules:
  kafka_data:
  kafka_secrets:
  kafka_config:
  redis_data: